<?php
/**
 * Created by PhpStorm.
 * User: trentrogers
 * Date: 5/24/16
 * Time: 12:54 PM
 */

namespace Tests;

use Laracore\Repository\Relation\RelationRepository;
use Illuminate\Database\Eloquent\Model;

class RelationRepositoryTest extends TestCase
{
    /**
     * @var RelationRepository
     */
    protected $relationRepository;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

//        $repository = \Mockery::mock(RelationRepository::class);

        $repository = new RelationRepository();

        $this->relationRepository = $repository;
    }

    public function testSetRelation()
    {
        $model = \Mockery::mock(Model::class);
        $model->shouldReceive('setRelation')
            ->once()
            ->andReturnSelf();
        
        $result = $this->relationRepository->setRelation($model, 'stuff', 'things');

        $this->assertInstanceOf(Model::class, $result);
    }
    
    public function testSetRelations()
    {
        $model = \Mockery::mock(Model::class);
        $model->shouldReceive('setRelations')
            ->once()
            ->andReturnSelf();

        $result = $this->relationRepository->setRelations($model, 'stuff');

        $this->assertInstanceOf(Model::class, $result);
    }

    public function testSetTouchedRelations()
    {
        $model = \Mockery::mock(Model::class);
        $model->shouldReceive('setTouchedRelations')
            ->once()
            ->andReturnSelf();

        $result = $this->relationRepository->setTouchedRelations($model, 'stuff');
        $this->assertInstanceOf(Model::class, $result);
    }

//    public function

    public function tearDown()
    {
        parent::tearDown();
        \Mockery::close();
    }
}